[project]
name = "alpha"
version = "0.1.0"
description = "my research on computationally accelerated finance"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.1.0",
    "pandas>=2.3.3",
    "ruff>=0.14.5",
    "yfinance>=0.2.66",
]
